# Generated by Django 4.1.5 on 2023-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=112)),
                ('lastname', models.CharField(max_length=112)),
                ('email', models.CharField(max_length=112)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
