# Generated by Django 4.1.5 on 2023-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_alter_contact_email_alter_contact_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=120),
        ),
    ]
